# Generated by Django 2.1.7 on 2019-04-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190328_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(default='', help_text='Content for description meta tag', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(default=1, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255),
            preserve_default=False,
        ),
    ]
