# Generated by Django 2.2.1 on 2019-05-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default='', help_text='Content for description meta tag', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='credit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
