# Generated by Django 2.1.7 on 2019-04-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190405_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='credit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
